### ISSUE TITLE
Tabpage Roadmap

### ISSUE THREAD

**Issue by Kogia-sima** [Kogia-sima/bufftab.vim#5]
With release of version 1.0, bufftab.vim is planning to support enhanced tabpage feature. Utilizing builtin tabpage feature, bufftab.vim enables to switching another tabpage as if switching between multiple vim instances.

The following features will be implemented.
- [ ] Stabilize
- [ ] Only buffers in current tab are shown in tabline.
- [ ] Tabpage numbers are shown in right side of tabline, only when there are two or more tabpages.
- [ ] Tabpage switching functionalities
- [ ] Automatically close the current tabpage when the last buffer in the current tabpage is goint to be deleted.
- [ ] When loading the buffer which already exists in another buffer, bufftab.vim should append it to the buffer list in the current tabpage.

**Comment by Kogia-sima** [comment]
There should be more consideration about the usage of builtin tabpage function. Some people may want to use tabpages for another purpose.
